/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(getGreeting());
        //lambda
        Runnable r =() -> System.out.println(getGreeting());
        new Thread(r).start();
    }

}
